apiVersion: v1
kind: Pod
metadata:
  name: infocare-prometheus
  labels:
    app.kubernetes.io/name: infocare-prometheus
spec:
  imagePullSecrets:
  - name: ghcr-login-secret
  containers:
  - name: prometheus-container
    image: docker.io/prom/prometheus:v2.47.0
    args:
      - --web.enable-remote-write-receiver
      - --config.file=/etc/prometheus/prometheus.yml
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 9090
        name: prometheus-port
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-cluster-ip
spec:
  selector:
    app.kubernetes.io/name: infocare-prometheus
  ports:
  - name: prometheus-port
    protocol: TCP
    port: 9090
    targetPort: prometheus-port