apiVersion: v1
kind: Pod
metadata:
  name: ic-prometheus
  labels:
    app.kubernetes.io/name: ic-prometheus
spec:
  containers:
  - name: prometheus-container
    image: docker.io/prom/prometheus:v2.47.0
    args:
      - --web.enable-remote-write-receiver
      - --config.file=/etc/prometheus/prometheus.yml
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 9090
        name: ic-prom-port
---
apiVersion: v1
kind: Service
metadata:
  name: ic-prom-cip
spec:
  selector:
    app.kubernetes.io/name: ic-prometheus
  ports:
  - name: ic-prom-port
    protocol: TCP
    port: 9090
    targetPort: ic-prom-port