apiVersion: v1
kind: ConfigMap
metadata:
  name: ic-remote-agent-cm
data:
  config.river: |
    logging {
        level = "warn"
    }
    prometheus.scrape "default" {
        scrape_interval = "10s"
        targets = concat(
                [{
                        job         = "db2metrics",
                        __address__ = "ic-db2-exporters-cip:9953",
                }],
        )

        forward_to = [
                prometheus.remote_write.local_prom.receiver,
        ]
    }
    prometheus.remote_write "local_prom" {
        endpoint {
                url = "http://ic-prom-cip:9090/api/v1/write"
        }
    }

---

apiVersion: v1
kind: Pod
metadata:
  name: ic-remote-agent
  labels:
    app.kubernetes.io/name: ic-remote-agent
spec:
  containers:
  - name: ic-remote-agent-container
    image: docker.io/infocura/infocare-remote-agent:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - name: ic-agent-port
        containerPort: 12345
    volumeMounts:
    - name: config-volume
      mountPath: "/etc/agent/config.river"
      subPath: config.river
  volumes:
  - name: config-volume
    configMap: 
      name: ic-remote-agent-cm

---

apiVersion: v1
kind: Service
metadata:
  name: ic-remote-agent-cip
spec:
  selector:
    app: ic-remote-agent
  ports:
  - port: 12345
    targetPort: ic-agent-port
